os: linux
dist: trusty
os:
    - linux
    - osx
before_install:
    - if test "$TRAVIS_OS_NAME" = "linux" ; then sudo apt-get update -qq ; sudo apt-get install -y ack-grep cpanminus libperl-dev make perl python-glade2 python-gnome2 python-gnome2-dev python-gtk2 python-setuptools python-tk python3 python3-pip python3-setuptools python3-tk ; sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep ; fi
    - if test "$TRAVIS_OS_NAME" = "osx" ; then brew update; fi
    - if test "$TRAVIS_OS_NAME" = "osx" ; then brew list python &>/dev/null || brew install python; fi
    - if test "$TRAVIS_OS_NAME" = "osx" ; then brew list python3 &>/dev/null || brew install python3; fi
    - if test "$TRAVIS_OS_NAME" = "osx" ; then brew install pyenv-virtualenv; fi
    - if test "$TRAVIS_OS_NAME" = "osx" ; then brew bundle ; brew link gettext --force ; export PATH="$PATH:/usr/local/bin" ; export DYLD_LIBRARY_PATH="/usr/local/opt/curl/lib:/usr/local/opt/openssl/lib:${DYLD_LIBRARY_PATH}" ; export PATH="/usr/local/opt/openssl/bin:$PATH" ; export LDFLAGS="$LDFLAGS -L/usr/local/opt/openssl/lib" ; export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/openssl/include" ; export CPPFLAGS="$CPPFLAGS -I$(brew --prefix openssl)/include" PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig:$PKG_CONFIG_PATH" LDFLAGS="$LDFLAGS -L$(brew --prefix openssl)/lib" ;fi
install:
    - sudo cpanm Code::TidyAll::Plugin::Flake8 Perl::Tidy Test::Code::TidyAll Test::Differences Test::TrailingSpace
    - export PY_MODS='pycotap random2 six'
    - "`which python3` -m pip install --upgrade flake8 $PY_MODS"
    - "sudo /usr/bin/python3 -m pip install --upgrade $PY_MODS || true"
    - "sudo `which python2` -m pip install --upgrade $PY_MODS"
    - which python
    - which python2
language: python
python:
    - "3.6"
matrix:
    exclude:
        - os: osx
          language: python
    include:
        - os: osx
          language: generic
          env: TOXENV=py35
script: "sh -x scripts/travis-ci-build"
